# Generated by Django 4.2.30 on 2026-09-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitordevice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='exhibitordevice',
            name='last_login',
        ),
        migrations.CreateModel(
            name='ExhibitorDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exhibitors.exhibitordevice')),
            ],
        ),
    ]
